tensor(196)
1214214
Exception ignored in: <function _releaseLock at 0x7fde17b7bd00>
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 228, in _releaseLock
    def _releaseLock():
KeyboardInterrupt:
Exception ignored in: <function _releaseLock at 0x7fde17b7bd00>
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 228, in _releaseLock
    def _releaseLock():
KeyboardInterrupt:
tensor(7026)
33873
Traceback (most recent call last):
  File "/home/kaustubh/Code3/cov_tester.py", line 133, in <module>
    main(data_path=data_path,batch_size=batch_size,num_epochs=num_epochs,learning_rate=learning_rate,model_path=model_path)
  File "/home/kaustubh/Code3/cov_tester.py", line 128, in main
    train_emb(model, train_emb_loader, criterion, optimizer, num_epochs=num_epochs,device=torch.device('cuda'),test_loader = test_emb_loader)
  File "/home/kaustubh/Code3/cov_help.py", line 427, in train_emb
    acc = test_model(model,test_loader,device=device)
  File "/home/kaustubh/Code3/cov_help.py", line 436, in test_model
    for data in test_loader:
  File "/home/kaustubh/llm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 441, in __iter__
    return self._get_iterator()
  File "/home/kaustubh/llm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/kaustubh/llm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1024, in __init__
    index_queue = multiprocessing_context.Queue()  # type: ignore[var-annotated]
  File "/usr/lib/python3.10/multiprocessing/context.py", line 102, in Queue
    from .queues import Queue
  File "<frozen importlib._bootstrap>", line 408, in parent
KeyboardInterrupt