Traceback (most recent call last):
  File "/home/kaustubh/Code3/cov_trainer.py", line 63, in <module>
    main(data_path=data_path,batch_size=batch_size,num_epochs=num_epochs,learning_rate=learning_rate,train_flag=train_flag)
  File "/home/kaustubh/Code3/cov_trainer.py", line 58, in main
    wandb.log_artifact(net)
  File "/home/kaustubh/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 370, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/kaustubh/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 360, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kaustubh/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2830, in log_artifact
    return self._log_artifact(
  File "/home/kaustubh/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2965, in _log_artifact
    artifact, aliases = self._prepare_artifact(
  File "/home/kaustubh/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 3065, in _prepare_artifact
    raise ValueError(
ValueError: You must pass an instance of wandb.Artifact or a valid file path to log_artifact