
**Starting data processing**
48626
** Formed Tensors and starting model training**
tensor(1.0356)
tensor(0.3589)
  0%|                                                                                                                                                                                           | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/raid/ganesh/racha_suraj/SF_test/Power-Mechanism-new/Adult_income/income_train.py", line 130, in <module>
    train_model_priv(net,trainloader,x_test_tensor,y_test_tensor,optimizer,epochs,0.82,device= device,print_cond = True,only_reg_flag=args.only_reg_flag,lr_schedular =None,lambda_loss=args.lambda_loss,max_steps=args.max_steps)
  File "/raid/ganesh/racha_suraj/SF_test/Power-Mechanism-new/Adult_income/utils.py", line 266, in train_model_priv
    wandb.log({"loss": loss.item(),"loss_reg":loss_reg.item()})
                                              ^^^^^^^^
UnboundLocalError: cannot access local variable 'loss_reg' where it is not associated with a value