tensor(44481)
4096
Exception ignored in: <function _releaseLock at 0x7f6fec9a7d90>
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 228, in _releaseLock
    def _releaseLock():
KeyboardInterrupt:
Traceback (most recent call last):
  File "/home/kaustubh/Code3/Forrest Cover Type/cov_tester_2.py", line 144, in <module>
    main(data_path=data_path,batch_size=batch_size,num_epochs=num_epochs,learning_rate=learning_rate,model_path=model_path)
  File "/home/kaustubh/Code3/Forrest Cover Type/cov_tester_2.py", line 139, in main
    train_emb(model, train_emb_loader, criterion, optimizer, num_epochs=num_epochs,device=torch.device('cuda'),test_loader = test_emb_loader,test_total_loader = None)
  File "/home/kaustubh/Code3/Forrest Cover Type/cov_help.py", line 436, in train_emb
    acc = test_model(model,test_loader,device=device)
  File "/home/kaustubh/Code3/Forrest Cover Type/cov_help.py", line 449, in test_model
    for data in test_loader:
  File "/home/kaustubh/llm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/kaustubh/llm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1317, in _next_data
    self._shutdown_workers()
  File "/home/kaustubh/llm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1442, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt